version: '3.7'

services:

  postgres_custom:
    image: postgres:13
    environment:
      POSTGRES_USER: boaz
      POSTGRES_PASSWORD: qwer1234!@
      POSGRES_DB: baekjoon
      TZ: Asia/Seoul
    volumes:
      - postgres-custom-db-volume:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres-custom-db-volume: