version: '3'

services:
#  splash:
#    image: scrapinghub/splash
#    ports:
#      - "8050:8050"

  scrapy:
    image: baekjoon_scraper
    volumes:
      - .:/app
    command: ["python", "crawler_process.py", "beakjoon_user_detail"]